import { REPAIR_STATUS, REQUEST_STATUS } from "./constants";

export type Tone = "neutral" | "good" | "warning" | "serious" | "critical" | "accent";

/** Timeline-dot fill for a given tone — the same tone→color mapping as
 * Badge, just a filled circle instead of a pill. Shared by RequestDetailModal
 * and RepairDetailModal's activity timelines. */
export function toneDotClass(tone: Tone): string {
  switch (tone) {
    case "good":
      return "bg-good";
    case "warning":
      return "bg-warning";
    case "serious":
      return "bg-serious";
    case "critical":
      return "bg-critical";
    case "accent":
      return "bg-series-1";
    default:
      return "bg-ink-muted";
  }
}

/** Plain (non-pill) text color for a tone — same palette as Badge's label
 * color, for signals like a dwell meter or due-date readout that sit next
 * to an already-visible status Badge and shouldn't carry a second pill. */
export function toneTextClass(tone: Tone): string {
  switch (tone) {
    case "good":
      return "text-good";
    case "warning":
      return "text-[#8a5a00] dark:text-warning";
    case "serious":
      return "text-[#9a3f1c] dark:text-serious";
    case "critical":
      return "text-critical";
    case "accent":
      return "text-series-1";
    default:
      return "text-ink-secondary";
  }
}

export function requestStatusTone(statusId: number | null): Tone {
  switch (statusId) {
    case REQUEST_STATUS.ACCEPTED:
      return "accent";
    case REQUEST_STATUS.COMPLETED:
      return "good";
    case REQUEST_STATUS.DENIED:
      return "critical";
    default:
      return "neutral";
  }
}

/** Repair statuses (11 values) fold into 5 reserved status tones by meaning,
 * rather than importing the table's arbitrary per-row hex into UI chrome. */
export function repairStatusTone(statusId: number | null): Tone {
  switch (statusId) {
    case REPAIR_STATUS.RECEIVED:
      return "neutral";
    case 7: // On Hold
      return "warning";
    case REPAIR_STATUS.READY_FOR_RELEASE:
      return "good";
    case REPAIR_STATUS.RELEASED:
    case 11: // Closed
      return "neutral";
    case 10: // Cancelled
      return "critical";
    default:
      return "accent"; // Pending / In Progress / Diagnosing / Repairing / Waiting for Parts
  }
}

/** Keyed off `item_statuses.code` rather than id — those ids are
 * DB-generated by the migration's seed data, not fixed constants like
 * REQUEST_STATUS/REPAIR_STATUS, so code is the stable thing to switch on. */
export function itemStatusTone(code: string | null | undefined): Tone {
  switch (code) {
    case "in_use":
      return "accent";
    case "under_repair":
      return "warning";
    case "missing":
      return "critical";
    case "in_storage":
    case "decommissioned":
    default:
      return "neutral";
  }
}

export function mrStatusTone(status: string | null | undefined): Tone {
  switch (status) {
    case "active":
      return "accent";
    case "returned":
      return "good";
    case "transferred":
    default:
      return "neutral";
  }
}
